### ISSUE TITLE
:okbuck FAILED  FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':okbuck'. > /Users/foobar/AndroidStudioProjects/mylibrary/BUCK (No such file or directory)

### ISSUE THREAD

**Issue by nicay** [Piasy/OkBuck#31]
build failed and throw me above message. How to solve it? thanks!

**Comment by Piasy** [comment]
@nicay Could you please provide the output of `./gradlew okbuck --stacktrace`? Thanks!

**Comment by nicay** [comment]
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':okbuck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: java.io.FileNotFoundException: /Users/foobar/AndroidStudioProjects/testAppdroidGradle/mylibrary/BUCK (No such file or directory)
        at com.github.piasy.okbuck.OkBuckGradlePlugin.applyWithBuildVariant(OkBuckGradlePlugin.groovy:140)
        at com.github.piasy.okbuck.OkBuckGradlePlugin$_apply_closure3.doCall(OkBuckGradlePlugin.groovy:72)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:548)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:529)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 54 more


BUILD FAILED
```

actually, my app is called `testApp`, and it includes a library module called `MyAndroidGradle/mylibrary`, but the path shown in error message seems odd.

**Comment by Piasy** [comment]
@nicay Well, that's really strange, could you please check what's the exact path of your library `mylibrary ` through finder or a terminal?

**Comment by nicay** [comment]
@Piasy the path is `/Users/foobar/AndroidStudioProjects/MyAndroidGradle/mylibrary`

**Comment by Piasy** [comment]
@nicay That's really out of my mind... could you please try this bug fix version of OkBuck: `0.3.0-issue-31`? Just put this line into your top level build.gradle file: 
```gradle
classpath "com.github.piasy:okbuck-gradle-plugin:0.3.0-issue-31"
``` 
Try this version and please provide the full output of `./gradlew okbuck --stacktrace`, thanks!

**Comment by nicay** [comment]
@Piasy This bug fix version works fine and now build successful. Thanks!

**Comment by Piasy** [comment]
@nicay Could you please paste the output of `./gradlew okbuck --stacktrace` so that I can figure out what went wrong with the former version?

**Comment by nicay** [comment]
@Piasy 
```
get app's buildConfigField:
get mylibrary’s buildConfigField:
issue #31 root project path: /Users/foobar/AndroidStudioProjects/testApp
issue #31 sub project path: /Users/foobar/AndroidStudioProjects/MyAndroidGradle/mylibrary
issue #31 project path diff: droidGradle/mylibrary
issue #31 final path: /Users/foobar/AndroidStudioProjects/testAppdroidGradle/mylibrary/BUCK
issue #31 root project path: /Users/foobar/AndroidStudioProjects/testApp
issue #31 sub project path: /Users/foobar/AndroidStudioProjects/testApp/app
issue #31 project path diff: /app
issue #31 final path: /Users/foobar/AndroidStudioProjects/testApp/app/BUCK
```

**Comment by Piasy** [comment]
@nicay Got it, you reference a module which locate outside your root project folder, right?

**Comment by nicay** [comment]
@Piasy yes, that is a library module which locate somewhere.

**Comment by Piasy** [comment]
@nicay Well, the issue fix version won't fail when execute `./gradlew okbuck`, but I think `buck install` will fail because your library module locate somewhere outside your root project folder, if so, you can only move it in.

**Comment by nicay** [comment]
@Piasy yes, `buck install` failed, but I don't want the module be putted inside my app, which messes the app structure.

**Comment by Piasy** [comment]
@nicay Does the following structure bother you?
--testApp
----app
----mylibrary
This the standard gradle project structure, where library and app module are siblings.

**Comment by nicay** [comment]
@Piasy since `mylibrary ` will be used by other project, if i do so, I need to copy that library module into the new project folder everytime when the new project depends on `mylibrary`.

**Comment by Piasy** [comment]
@nicay Oh, got it, maybe you can pack your library into a jar/aar file, and new project depends it via prebuilt jar/aar file.
