### ISSUE TITLE
Support RetroLambda

### ISSUE THREAD

**Issue by sdwilsh** [Piasy/OkBuck#32]
From https://github.com/Piasy/OkBuck/wiki/Known-caveats#incompatible-with-retrolambda, it says that Buck doesn't compile with Java 8.  Buck does, although we haven't stated that it does yet because we don't yet have CI setup for it to make sure we don't break it in the future.

If that's the only thing that is blocking you, it should just work.

**Comment by Piasy** [comment]
@sdwilsh Thanks for your remind, I'll give it a trial.

**Comment by Piasy** [comment]
@sdwilsh Could you please give an example that make RetroLambda work with BUCK? I find this link: https://groups.google.com/forum/#!topic/buck-build/tpBERd8tcIc, which gives an example:
```python
java_library(
  name = 'example',
  srcs = glob(['*.java']),
  post_process_commands = ['your-reweaver'],
)
```
 but `java_library` rule doesn't accept `post_process_commands` argument.

**Comment by sdwilsh** [comment]
It's `postprocess_classes_commands` (you can see this by looking at `JavaLibraryDescription.Arg`).

**Comment by Piasy** [comment]
@sdwilsh Dear sir, after several trials, I finally make buck work with RetroLambda for the `:libraries:javalibrary` module(`buck build libraries/javalibrary:src` succeed, and the class files inside `buck-out/bin/libraries/javalibrary/lib__src__classes` are in Java 7 format), but when I try to build `:dummylibrary` and `:app` module, it fails with  the error message below:
```java
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found.
```
I google this error but can't find an explanation or solution, could you please give me some help? The code base is [issue-32 branch](https://github.com/Piasy/OkBuck/tree/2da152e34276de2fcab52d1d7783de462ada399a).

**Comment by aphexcx** [comment]
Sorry to resurrect this, but is this now officially supported? If so, how? I'm converting an Android Studio + Gradle + gradle-retrolambda project to Buck as we speak and this seems to be my final obstacle.

**Comment by Piasy** [comment]
@aphexcx Just use the latest version of OkBuck, you don't need any extra configuration.

**Comment by aphexcx** [comment]
Hmm, I'm still getting the famous `java.lang.invoke.MethodType not found` exception:
```
An exception has occurred in the compiler (1.8.0_74). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found
```
Here's my build.gradle: 
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0-beta1'
        classpath 'com.uber:okbuck:0.13.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

apply plugin: 'com.uber.okbuck'
```

Here's my app's app/build.gradle: 
```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.22.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.1'
        classpath 'me.tatarka:gradle-retrolambda:3.4.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'

    }
}
apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.jakewharton.butterknife'
apply plugin: 'io.fabric'
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'com.getkeepsafe.dexcount'
```

Here's the full output of `./buckw install --run //app:bin_alphaDebug`: 
```
./buckw install --run //app:bin_alphaDebug
 CHANGES DETECTED IN: 
app/build.gradle

 RUNNING OKBUCK... 

 DELETED OLD BUCK FILES 
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/aphex/android-ndk-r10e.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-19')
Observed package id 'add-ons;addon-google_apis-google-24' in inconsistent location '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24-1' (Expected '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24')
Already observed package id 'add-ons;addon-google_apis-google-24' in '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24'. Skipping duplicate at '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24-1'
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/aphex/android-ndk-r10e.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
WARNING: Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
:buildDepCache
:okbuckSetupTask
:okbuck

BUILD SUCCESSFUL

Total time: 2.596 secs

 PROCEEDING WITH BUCK 

An exception has occurred in the compiler (1.8.0_74). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

BUILD FAILED: //app:src_alphaDebug failed with exit code 1:
javac
stderr: An exception has occurred in the compiler (1.8.0_74). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.lang.invoke.MethodType not found

[-] PROCESSING BUCK FILES...FINISHED 0.2s [100%] 🐌  File added
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 4.0s [100%] (364/367 JOBS, 0 UPDATED, 0 [0.0%] CACHE MISS)

```

What do you think? Much appreciated!

**Comment by Piasy** [comment]
That's wired, it seems `rt.jar` is missing from the classpath, @kageiit could you please give a look on it?

**Comment by aphexcx** [comment]
@kageiit Would appreciate your input!

**Comment by kageiit** [comment]
Did you try the latest version of okbuck? it adds an rt-stub.jar to the compilation classpath when using retrolambda to make these symbols available. okbuck sample uses it fine and so do folks at airbnb cc @felipecl

**Comment by kageiit** [comment]
@aphexcx can you check if your rule has a `provided_deps` entry for `rt-stub.jar`?

**Comment by aphexcx** [comment]
Hmm, it doesn't! Am I looking in the right place? I'm looking at the `./app/BUCK` file, and since I'm running `./buckw install --run //app:bin_alphaDebug`, I'm looking at this rule:
```
android_binary(
	name = 'bin_alphaDebug',
	manifest = ':manifest_alphaDebug',
	keystore = '//.okbuck/keystore/app:key_store_alphaDebug.keystore',
	use_split_dex = True,
	linear_alloc_hard_limit = 7194304,
	manifest_entries = {
		'placeholders': {
			'applicationId': 'com.postmates.android.courier.alpha',
		},
	},
	includes_vector_drawables = True,
	deps = [
		':res_alpha',
		':res_main',
		':src_alphaDebug',
	],
	visibility = [
		'PUBLIC',
	],
)
```

And here's the `src_alphaDebug` rule:
```
android_library(
	name = 'src_alphaDebug',
	srcs = glob([
		'src/main/java/**/*.java',
	]),
	manifest = 'build/okbuck/alphaDebug/AndroidManifest.xml',
	annotation_processors = [
		'butterknife.compiler.ButterKnifeProcessor',
		'dagger.internal.codegen.ComponentProcessor',
	],
	annotation_processor_deps = [
		':apt_jar_alphaDebug',
	],
	provided_deps = [
		'//.okbuck/cache:com.google.auto.auto-common-0.6.jar',
		'//.okbuck/cache:com.google.auto.service.auto-service-1.0-rc2.jar',
		'//.okbuck/cache:com.google.dagger.dagger-compiler-2.0.2.jar',
		'//.okbuck/cache:com.google.dagger.dagger-producers-2.0-beta.jar',
		'//.okbuck/cache:com.google.guava.guava-18.0.jar',
		'//.okbuck/cache:com.jakewharton.butterknife-compiler-8.4.0.jar',
		'//.okbuck/cache:com.squareup.javapoet-1.7.0.jar',
		'//.okbuck/cache:org.glassfish.javax.annotation-10.0-b28.jar',
	],
	source = '8',
	target = '8',
	final_r_name = 'R2',
	deps = [
		'//.okbuck/cache:com.android.support.animated-vector-drawable-25.0.0.aar',
		'//.okbuck/cache:com.android.support.appcompat-v7-25.0.0.aar',
		'//.okbuck/cache:com.android.support.cardview-v7-24.2.1.aar',
		'//.okbuck/cache:com.android.support.design-24.2.1.aar',
		'//.okbuck/cache:com.android.support.multidex-1.0.1.aar',
		'//.okbuck/cache:com.android.support.percent-24.2.1.aar',
		'//.okbuck/cache:com.android.support.recyclerview-v7-24.2.1.aar',
		'//.okbuck/cache:com.android.support.support-annotations-25.0.0.jar',
		'//.okbuck/cache:com.android.support.support-compat-25.0.0.aar',
		'//.okbuck/cache:com.android.support.support-core-ui-25.0.0.aar',
		'//.okbuck/cache:com.android.support.support-core-utils-25.0.0.aar',
		'//.okbuck/cache:com.android.support.support-fragment-25.0.0.aar',
		'//.okbuck/cache:com.android.support.support-media-compat-25.0.0.aar',
		'//.okbuck/cache:com.android.support.support-v13-24.2.1.aar',
		'//.okbuck/cache:com.android.support.support-v4-25.0.0.aar',
		'//.okbuck/cache:com.android.support.support-vector-drawable-25.0.0.aar',
		'//.okbuck/cache:com.crashlytics.sdk.android.answers-1.3.10.aar',
		'//.okbuck/cache:com.crashlytics.sdk.android.beta-1.2.2.aar',
		'//.okbuck/cache:com.crashlytics.sdk.android.crashlytics-2.6.5.aar',
		'//.okbuck/cache:com.crashlytics.sdk.android.crashlytics-core-2.3.14.aar',
		'//.okbuck/cache:com.eftimoff.android-pathview-1.0.8.aar',
		'//.okbuck/cache:com.facebook.fresco.drawee-0.14.1.aar',
		'//.okbuck/cache:com.facebook.fresco.fbcore-0.14.1.aar',
		'//.okbuck/cache:com.facebook.fresco.fresco-0.14.1.aar',
		'//.okbuck/cache:com.facebook.fresco.imagepipeline-0.14.1.aar',
		'//.okbuck/cache:com.facebook.fresco.imagepipeline-base-0.14.1.aar',
		'//.okbuck/cache:com.facebook.fresco.imagepipeline-okhttp3-0.14.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-base-10.0.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-basement-10.0.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-gcm-10.0.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-iid-10.0.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-location-10.0.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-maps-10.0.1.aar',
		'//.okbuck/cache:com.google.android.gms.play-services-tasks-10.0.1.aar',
		'//.okbuck/cache:com.google.code.findbugs.jsr305-3.0.1.jar',
		'//.okbuck/cache:com.google.code.gson.gson-2.6.1.jar',
		'//.okbuck/cache:com.google.dagger.dagger-2.0.2.jar',
		'//.okbuck/cache:com.jakewharton.butterknife-8.4.0.aar',
		'//.okbuck/cache:com.jakewharton.butterknife-annotations-8.4.0.jar',
		'//.okbuck/cache:com.jakewharton.rxbinding.rxbinding-0.4.0.aar',
		'//.okbuck/cache:com.jakewharton.threetenabp.threetenabp-1.0.4.aar',
		'//.okbuck/cache:com.jumio.android.core-2.4.0.aar',
		'//.okbuck/cache:com.jumio.android.javadoc-2.4.0.jar',
		'//.okbuck/cache:com.jumio.android.nv-2.4.0.aar',
		'//.okbuck/cache:com.jumio.android.nv-barcode-2.4.0.aar',
		'//.okbuck/cache:com.jumio.android.nv-barcode-vision-2.4.0.aar',
		'//.okbuck/cache:com.jumio.android.nv-mrz-2.4.0.aar',
		'//.okbuck/cache:com.jumio.android.nv-nfc-2.4.0.aar',
		'//.okbuck/cache:com.jumio.android.nv-ocr-2.4.0.aar',
		'//.okbuck/cache:com.mparticle.android-core-4.9.1.aar',
		'//.okbuck/cache:com.orhanobut.logger-1.15.aar',
		'//.okbuck/cache:com.parse.bolts.bolts-tasks-1.4.0.jar',
		'//.okbuck/cache:com.squareup.okhttp3.logging-interceptor-3.4.1.jar',
		'//.okbuck/cache:com.squareup.okhttp3.okhttp-3.4.1.jar',
		'//.okbuck/cache:com.squareup.okio.okio-1.9.0.jar',
		'//.okbuck/cache:com.squareup.picasso.picasso-2.5.2.jar',
		'//.okbuck/cache:com.squareup.retrofit2.adapter-rxjava-2.0.0.jar',
		'//.okbuck/cache:com.squareup.retrofit2.converter-gson-2.0.0.jar',
		'//.okbuck/cache:com.squareup.retrofit2.converter-scalars-2.0.0.jar',
		'//.okbuck/cache:com.squareup.retrofit2.retrofit-2.0.0.jar',
		'//.okbuck/cache:com.tbruyelle.rxpermissions.rxpermissions-0.7.0.aar',
		'//.okbuck/cache:com.trello.rxlifecycle-1.0.jar',
		'//.okbuck/cache:com.trello.rxlifecycle-android-1.0.aar',
		'//.okbuck/cache:com.trello.rxlifecycle-components-1.0.aar',
		'//.okbuck/cache:com.wdullaer.swipeactionadapter-2.0.0.aar',
		'//.okbuck/cache:io.fabric.sdk.android.fabric-1.3.14.aar',
		'//.okbuck/cache:io.reactivex.rxandroid-1.1.0.aar',
		'//.okbuck/cache:io.reactivex.rxjava-1.2.1.jar',
		'//.okbuck/cache:io.vokal.lint.rxlifecycle-1.0.2.aar',
		'//.okbuck/cache:javax.inject.javax.inject-1.jar',
		'//.okbuck/cache:nl.littlerobots.rxlint.rxlint-1.0.aar',
		'//.okbuck/cache:org.threeten.threetenbp-1.3.2-no-tzdb.jar',
		'//.okbuck/cache:uk.co.chrisjenx.calligraphy-2.2.0.aar',
		'//core-android:res_main',
		'//core-android:src_release',
		':build_config_alphaDebug',
		':res_alpha',
		':res_main',
	],
	visibility = [
		'PUBLIC',
	],
)
```

**Comment by kageiit** [comment]
The rt-stub.jar is added automatically if the project is applying the retrolambda gradle plugin

https://github.com/uber/okbuck/blob/9dc32de31c77130fba5ca31e9184c93406eb9f92/buildSrc/src/main/groovy/com/uber/okbuck/composer/java/JavaLibraryRuleComposer.groovy#L29

If you check the generated files for okbuck samples, this entry is present. You should check if you have applied the retrolambda gradle plugin on that module

**Comment by aphexcx** [comment]
That's really strange. The app project, as you can see from the gradle file I posted above, is applying the retrolambda plugin. 

```
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        jcenter()
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.22.0'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.1'
        classpath 'me.tatarka:gradle-retrolambda:3.4.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'

    }
}
apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
...
```
Could OkBuck not be recognizing that somehow?

**Comment by kageiit** [comment]
I am not sure why retrolambda is not being detected. Can you try to debug on your project by printing out if the plugin is applied or not by forking okbuck locally?

**Comment by kageiit** [comment]
Another option is to take the `rt-stub.jar` from the okbuck repo and just add it locally to your project as a `provided` dependency as a local jar. That should make it work as well

**Comment by aphexcx** [comment]
I grabbed `rt-stub.jar` and added it to my libs folder. Then I added this to `build.gradle`:
```
dependencies {
    provided files('libs/rt-stub.jar')
```
This gets me further into the build, but then it fails with this:
```
$ ./buckw install --run //app:bin_alphaDebug 
 CHANGES DETECTED IN: 
build.gradle

 RUNNING OKBUCK... 

 DELETED OLD BUCK FILES 
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/aphex/android-ndk-r10e.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Observed package id 'add-ons;addon-google_apis-google-19' in inconsistent location '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-19-1' (Expected '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-19')
Observed package id 'add-ons;addon-google_apis-google-24' in inconsistent location '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24-1' (Expected '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24')
Already observed package id 'add-ons;addon-google_apis-google-24' in '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24'. Skipping duplicate at '/Users/aphex/Library/Android/sdk/add-ons/addon-google_apis-google-24-1'
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/aphex/android-ndk-r10e.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
Jack is disabled, but one of the plugins you are using supports Java 8 language features.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
:buildDepCache
:setupGroovyHome
:okbuckSetupTask
:okbuck

BUILD SUCCESSFUL

Total time: 3.738 secs

 PROCEEDING WITH BUCK 


UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
        at com.android.dx.command.dexer.Main.processClass(Main.java:780)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:746)
        at com.android.dx.command.dexer.Main.access$1200(Main.java:91)
        at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1688)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:700)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:597)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:324)
        at com.android.dx.command.dexer.Main.run(Main.java:295)
        at com.facebook.buck.android.DxStep.executeInProcess(DxStep.java:188)
        at com.facebook.buck.android.DxStep.execute(DxStep.java:163)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:47)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1399)
        at com.facebook.buck.rules.CachingBuildEngine.lambda$11(CachingBuildEngine.java:340)
        at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
        at com.android.dx.command.dexer.Main.parseClass(Main.java:792)
        at com.android.dx.command.dexer.Main.access$1600(Main.java:91)
        at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1727)
        at com.android.dx.command.dexer.Main.processClass(Main.java:778)
        ... 23 more
1 error; aborting

BUILD FAILED: //app:src_alphaDebug#dex failed with exit code 1:
dx
[-] PROCESSING BUCK FILES...FINISHED 0.3s [100%] 🐌  File added
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 14.4s [100%] (367/369 JOBS, 1 UPDATED, 1 [0.3%] CACHE MISS)
```
Hmm.. seems like we're getting closer!

**Comment by kageiit** [comment]
This just means that retrolambda never ran on your app. Its better to debug why retrolambda is not getting applied to your project than use the workaround of adding rt stub jar

**Comment by aphexcx** [comment]
That's a good clue, then. I'm trying everything I can think of. What's confusing here is that Retrolambda *is* getting applied when I build with gradle, of course. If I had to guess, OkBuck is simply not recognizing that my project uses retrolambda, and so does not include rt-stub and doesn't run retrolambda. Now just to figure out why.

In the groovy file you linked, what determines `target.retrolambda`?
```
if (target.retrolambda) {
            providedDeps.add(RetrolambdaUtil.getRtStubJarRule())
        }
```

**Comment by kageiit** [comment]
`target.retrolamdba` is basically https://github.com/uber/okbuck/blob/master/buildSrc/src/main/groovy/com/uber/okbuck/core/model/java/JavaLibTarget.groovy#L59
