### ISSUE TITLE
an error happen when `gradlew okbuck`

### ISSUE THREAD

**Issue by qihigh** [Piasy/OkBuck#34]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okbuck'.
> Ambiguous method overloading for method com.github.piasy.okbuck.helper.CheckUtil#checkNotEmpty.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
        [interface java.util.List, class java.lang.String]
        [interface java.util.Set, class java.lang.String]

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':okbuck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method com.github.piasy.okbuck.helper.CheckUtil#checkNotEmpty.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
        [interface java.util.List, class java.lang.String]
        [interface java.util.Set, class java.lang.String]
        at com.github.piasy.okbuck.helper.CheckUtil$checkNotEmpty$0.callStatic(Unknown Source)
        at com.github.piasy.okbuck.rules.AndroidResourceRule.<init>(AndroidResourceRule.groovy:47)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator.createAndroidLibraryRules(XBuckFileGenerator.groovy:134)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator.this$3$createAndroidLibraryRules(XBuckFileGenerator.groovy)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator$this$3$createAndroidLibraryRules$1.callCurrent(Unknown Source)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator.generate(XBuckFileGenerator.groovy:69)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator$generate.call(Unknown Source)
        at com.github.piasy.okbuck.OkBuckGradlePlugin.applyWithBuildVariant(OkBuckGradlePlugin.groovy:132)
        at com.github.piasy.okbuck.OkBuckGradlePlugin$_apply_closure3.doCall(OkBuckGradlePlugin.groovy:72)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more


BUILD FAILED
```

**Comment by Piasy** [comment]
@qihigh Could you please provide the okbuck config in your top level build.gradle? Like below:
```gradle
okbuck {
...
}
```

**Comment by qihigh** [comment]
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        classpath "com.github.piasy:okbuck-gradle-plugin:0.3.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}


allprojects {
    repositories {
        jcenter()
    }
}

apply plugin: 'com.github.piasy.okbuck-gradle-plugin'

okbuck {
    target "android-23"
    overwrite true
    keystoreDir ".okbuck/keystore"
    signConfigName "release"
    resPackages = [
            dummylibrary: 'com.github.piasy.okbuck.example.dummylibrary',
            app: 'com.github.piasy.okbuck.example',
            anotherapp: 'com.github.piasy.okbuck.example.anotherapp',
            common: 'com.github.piasy.okbuck.example.common',
            emptylibrary: 'com.github.piasy.okbuck.example.empty',
    ]
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by Piasy** [comment]
@qihigh You should set your config according to your own project structure, not copy everything in this repo into your own project.

**Comment by qihigh** [comment]
Really thank you，It's done after fixed.

**Comment by Piasy** [comment]
@qihigh Thanks for try OkBuck! The confusing error message is actually a problem of OkBuck, I'll fix it later.

**Comment by qihigh** [comment]
Nice work
