### ISSUE TITLE
cant't buck work with android data-binding?

### ISSUE THREAD

**Issue by FtheGFW** [Piasy/OkBuck#43]
Error parsing resources to generate resource IDs for app/src/main/res.
com.facebook.buck.android.aapt.MiniAapt.ResourceParseException: Invalid definition of a resource: '@{userVM.avatar}'
com.facebook.buck.android.aapt.MiniAapt$ResourceParseException: Invalid definition of a resource: '@{userVM.avatar}'
        at com.facebook.buck.android.aapt.MiniAapt.processXmlFile(MiniAapt.java:411)
        at com.facebook.buck.android.aapt.MiniAapt.processXmlFilesForIds(MiniAapt.java:379)
        at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:143)
        at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
        at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:967)
        at com.facebook.buck.rules.CachingBuildEngine.access$600(CachingBuildEngine.java:88)
        at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:367)
        at com.facebook.buck.rules.CachingBuildEngine$1.apply(CachingBuildEngine.java:239)

**Comment by Piasy** [comment]
@FtheGFW Do you use data binding? Buck doesn't support data binding now.
