### ISSUE TITLE
执行buck install app 失败

### ISSUE THREAD

**Issue by emile2013** [Piasy/OkBuck#44]
@Piasy  
我这边用okbuck 集成gradle和buck，执行gradle okbuck 是Ok的，但执行buck install app命令抛出了以下错误：

buck install app
Using watchman.
Traceback (most recent call last):
  File "/usr/local/bin/buck/.bootstrap/_twitter_common_python/pex.py", line 223, in execute
    self.execute_entry(entry_point, args)
  File "/usr/local/bin/buck/.bootstrap/_twitter_common_python/pex.py", line 271, in execute_entry
    runner(entry_point)
  File "/usr/local/bin/buck/.bootstrap/_twitter_common_python/pex.py", line 288, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/buck/programs/buck.py", line 52, in <module>
  File "/usr/local/bin/buck/programs/buck.py", line 45, in main
  File "/usr/local/bin/buck/programs/buck_tool.py", line 130, in launch_buck
  File "/usr/local/bin/buck/programs/buck_tool.py", line 219, in launch_buckd
  File "/usr/local/bin/buck/programs/buck_tool.py", line 380, in _get_java_args
  File "/usr/local/bin/buck/programs/buck_package.py", line 40, in _get_resource
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 28: ordinal not in range(128)

**Comment by Piasy** [comment]
@emile2013 这看起来是BUCK运行出了问题，你的BUCK正确安装了吗？你试着按照[quick start](https://buckbuild.com/setup/quick_start.html)的教程过一遍，看看能不能成功？

**Comment by emile2013** [comment]
@Piasy 按 buck 的 quick start 是ok的，能编译部署到我的真机上。

**Comment by Piasy** [comment]
@emile2013 我google搜了下报错信息：
```bash
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 28: ordinal not in range(128)
```
你的这个工程路径名是不是有中文呀？

**Comment by emile2013** [comment]
@Piasy  是的，有中文目录，我现在改过来了，但是执行gradle okbuck ，module根目录没有生成BUCK文件。

**Comment by Piasy** [comment]
@emile2013 你加到QQ群里面聊吧？
