### ISSUE TITLE
gradle android tool 1.5找不到sign config

### ISSUE THREAD

**Issue by fengbugou** [Piasy/OkBuck#48]
1.3的时候是OK的，把1.3改成下面的1.5, gradlew okbuck就报错了
classpath 'com.android.tools.build:gradle:1.5.0'

trace 如下

:okbuckClean
:okbuck
<<< hashSetAddTraversalTest
1, 2, 3 ==> 123
3, 2, 1 ==> 123
2, 1, 3 ==> 123
hashSetAddTraversalTest >>>
==========>> overwrite mode is toggle on <<==========
Sub project 'app': /Users/dt/Developer/Code/Android/idea/Cl024/app
Sub project 'dtroidlib': /Users/dt/Developer/Code/Android/idea/Cl024/dtroidlib
app doesn't contain apt configuration
<<<<< app
        <<< debug
        >>>
        <<< release
        >>>
        <<< main
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.google.guava/guava/19.0-rc2/93e17f60bc524c2610b41c494bb829c11ca89436/guava-19.0-rc2.jar
                /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.1.1/cardview-v7-23.1.1.aar
                /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.1/recyclerview-v7-23.1.1.aar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/io.reactivex/rxandroid/1.0.1/563323d4f90cdb87d067fcf02b06c5d16bb1a258/rxandroid-1.0.1.aar
                /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.aar
                /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.aar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/org.jsoup/jsoup/1.8.3/65fd012581ded67bc20945d85c32b4598c3a9cf1/jsoup-1.8.3.jar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.trello/rxlifecycle/0.3.0/5304a47b85fd7250e14ad51104c8ab28dbbd8261/rxlifecycle-0.3.0.aar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.github.rahatarmanahmed/circularprogressview/2.4.0/45a7e00646af478a326912d77b4be1c964c307c4/circularprogressview-2.4.0.aar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.trello/rxlifecycle-components/0.3.0/b60d580c5d2bf5ea06a0c79a182d5d7846b1c6a1/rxlifecycle-components-0.3.0.aar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.jakewharton.rxbinding/rxbinding/0.2.0/97c550ecaf825c003b1b30cb1b754745fa79307a/rxbinding-0.2.0.aar
                /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/support-annotations/23.1.1/support-annotations-23.1.1.jar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.michaelpardo/activeandroid/3.1.0-SNAPSHOT/4ab7b0182975bc57c49efc5e0b3baa4a10e4ec08/activeandroid-3.1.0-SNAPSHOT.jar
                /Users/dt/Developer/Code/Android/idea/Cl024/dtroidlib/app-release.aar
                /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/design/23.1.1/design-23.1.1.aar
                /Users/dt/gradle_user_home/caches/modules-2/files-2.1/io.reactivex/rxjava/1.0.14/898f9ab61e2a23afd615f0b0389478bec86f49f9/rxjava-1.0.14.jar
        >>>
>>>>>
app's deps:
<<< final
        << debug
                //.okbuck/app:aar__design-23.1.1.aar, //.okbuck/app:aar__design-23.1.1.aar
                //.okbuck/app:jar__rxjava-1.0.14.jar
                //.okbuck/app:jar__jsoup-1.8.3.jar
                //.okbuck/app:aar__circularprogressview-2.4.0.aar, //.okbuck/app:aar__circularprogressview-2.4.0.aar
                //.okbuck/app:jar__activeandroid-3.1.0-SNAPSHOT.jar
                //.okbuck/app:aar__app-release.aar, //.okbuck/app:aar__app-release.aar
                //.okbuck/app:aar__appcompat-v7-23.1.1.aar, //.okbuck/app:aar__appcompat-v7-23.1.1.aar
                //.okbuck/app:aar__cardview-v7-23.1.1.aar, //.okbuck/app:aar__cardview-v7-23.1.1.aar
                //.okbuck/app:aar__support-v4-23.1.1.aar, //.okbuck/app:aar__support-v4-23.1.1.aar
                //.okbuck/app:jar__support-annotations-23.1.1.jar
                //.okbuck/app:jar__guava-19.0-rc2.jar
                //.okbuck/app:aar__rxbinding-0.2.0.aar, //.okbuck/app:aar__rxbinding-0.2.0.aar
                //.okbuck/app:aar__rxlifecycle-0.3.0.aar, //.okbuck/app:aar__rxlifecycle-0.3.0.aar
                //.okbuck/app:aar__rxlifecycle-components-0.3.0.aar, //.okbuck/app:aar__rxlifecycle-components-0.3.0.aar
                //.okbuck/app:aar__recyclerview-v7-23.1.1.aar, //.okbuck/app:aar__recyclerview-v7-23.1.1.aar
                //.okbuck/app:aar__rxandroid-1.0.1.aar, //.okbuck/app:aar__rxandroid-1.0.1.aar
        >>
        << release
                //.okbuck/app:aar__design-23.1.1.aar, //.okbuck/app:aar__design-23.1.1.aar
                //.okbuck/app:jar__rxjava-1.0.14.jar
                //.okbuck/app:jar__jsoup-1.8.3.jar
                //.okbuck/app:aar__circularprogressview-2.4.0.aar, //.okbuck/app:aar__circularprogressview-2.4.0.aar
                //.okbuck/app:jar__activeandroid-3.1.0-SNAPSHOT.jar
                //.okbuck/app:aar__app-release.aar, //.okbuck/app:aar__app-release.aar
                //.okbuck/app:aar__appcompat-v7-23.1.1.aar, //.okbuck/app:aar__appcompat-v7-23.1.1.aar
                //.okbuck/app:aar__cardview-v7-23.1.1.aar, //.okbuck/app:aar__cardview-v7-23.1.1.aar
                //.okbuck/app:aar__support-v4-23.1.1.aar, //.okbuck/app:aar__support-v4-23.1.1.aar
                //.okbuck/app:jar__support-annotations-23.1.1.jar
                //.okbuck/app:jar__guava-19.0-rc2.jar
                //.okbuck/app:aar__rxbinding-0.2.0.aar, //.okbuck/app:aar__rxbinding-0.2.0.aar
                //.okbuck/app:aar__rxlifecycle-0.3.0.aar, //.okbuck/app:aar__rxlifecycle-0.3.0.aar
                //.okbuck/app:aar__rxlifecycle-components-0.3.0.aar, //.okbuck/app:aar__rxlifecycle-components-0.3.0.aar
                //.okbuck/app:aar__recyclerview-v7-23.1.1.aar, //.okbuck/app:aar__recyclerview-v7-23.1.1.aar
                //.okbuck/app:aar__rxandroid-1.0.1.aar, //.okbuck/app:aar__rxandroid-1.0.1.aar
        >>
        << main
                //.okbuck/app:aar__design-23.1.1.aar, //.okbuck/app:aar__design-23.1.1.aar
                //.okbuck/app:aar__rxbinding-0.2.0.aar, //.okbuck/app:aar__rxbinding-0.2.0.aar
                //.okbuck/app:aar__circularprogressview-2.4.0.aar, //.okbuck/app:aar__circularprogressview-2.4.0.aar
                //.okbuck/app:aar__rxlifecycle-0.3.0.aar, //.okbuck/app:aar__rxlifecycle-0.3.0.aar
                //.okbuck/app:aar__rxlifecycle-components-0.3.0.aar, //.okbuck/app:aar__rxlifecycle-components-0.3.0.aar
                //.okbuck/app:aar__app-release.aar, //.okbuck/app:aar__app-release.aar
                //.okbuck/app:aar__recyclerview-v7-23.1.1.aar, //.okbuck/app:aar__recyclerview-v7-23.1.1.aar
                //.okbuck/app:aar__appcompat-v7-23.1.1.aar, //.okbuck/app:aar__appcompat-v7-23.1.1.aar
                //.okbuck/app:aar__cardview-v7-23.1.1.aar, //.okbuck/app:aar__cardview-v7-23.1.1.aar
                //.okbuck/app:aar__rxandroid-1.0.1.aar, //.okbuck/app:aar__rxandroid-1.0.1.aar
                //.okbuck/app:aar__support-v4-23.1.1.aar, //.okbuck/app:aar__support-v4-23.1.1.aar
        >>
>>>
<<< apt
>>>
<<< annotation processors
>>>
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/design/23.1.1/design-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/io.reactivex/rxjava/1.0.14/898f9ab61e2a23afd615f0b0389478bec86f49f9/rxjava-1.0.14.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/org.jsoup/jsoup/1.8.3/65fd012581ded67bc20945d85c32b4598c3a9cf1/jsoup-1.8.3.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.github.rahatarmanahmed/circularprogressview/2.4.0/45a7e00646af478a326912d77b4be1c964c307c4/circularprogressview-2.4.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.michaelpardo/activeandroid/3.1.0-SNAPSHOT/4ab7b0182975bc57c49efc5e0b3baa4a10e4ec08/activeandroid-3.1.0-SNAPSHOT.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/Code/Android/idea/Cl024/dtroidlib/app-release.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.1.1/cardview-v7-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/support-annotations/23.1.1/support-annotations-23.1.1.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.google.guava/guava/19.0-rc2/93e17f60bc524c2610b41c494bb829c11ca89436/guava-19.0-rc2.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.jakewharton.rxbinding/rxbinding/0.2.0/97c550ecaf825c003b1b30cb1b754745fa79307a/rxbinding-0.2.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.trello/rxlifecycle/0.3.0/5304a47b85fd7250e14ad51104c8ab28dbbd8261/rxlifecycle-0.3.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.trello/rxlifecycle-components/0.3.0/b60d580c5d2bf5ea06a0c79a182d5d7846b1c6a1/rxlifecycle-components-0.3.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.1/recyclerview-v7-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/io.reactivex/rxandroid/1.0.1/563323d4f90cdb87d067fcf02b06c5d16bb1a258/rxandroid-1.0.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/design/23.1.1/design-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/io.reactivex/rxjava/1.0.14/898f9ab61e2a23afd615f0b0389478bec86f49f9/rxjava-1.0.14.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/org.jsoup/jsoup/1.8.3/65fd012581ded67bc20945d85c32b4598c3a9cf1/jsoup-1.8.3.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.github.rahatarmanahmed/circularprogressview/2.4.0/45a7e00646af478a326912d77b4be1c964c307c4/circularprogressview-2.4.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.michaelpardo/activeandroid/3.1.0-SNAPSHOT/4ab7b0182975bc57c49efc5e0b3baa4a10e4ec08/activeandroid-3.1.0-SNAPSHOT.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/Code/Android/idea/Cl024/dtroidlib/app-release.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.1/appcompat-v7-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/cardview-v7/23.1.1/cardview-v7-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/support-v4/23.1.1/support-v4-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/support-annotations/23.1.1/support-annotations-23.1.1.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.google.guava/guava/19.0-rc2/93e17f60bc524c2610b41c494bb829c11ca89436/guava-19.0-rc2.jar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.jakewharton.rxbinding/rxbinding/0.2.0/97c550ecaf825c003b1b30cb1b754745fa79307a/rxbinding-0.2.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.trello/rxlifecycle/0.3.0/5304a47b85fd7250e14ad51104c8ab28dbbd8261/rxlifecycle-0.3.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/com.trello/rxlifecycle-components/0.3.0/b60d580c5d2bf5ea06a0c79a182d5d7846b1c6a1/rxlifecycle-components-0.3.0.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/Developer/lib/android-sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.1/recyclerview-v7-23.1.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
copying /Users/dt/gradle_user_home/caches/modules-2/files-2.1/io.reactivex/rxandroid/1.0.1/563323d4f90cdb87d067fcf02b06c5d16bb1a258/rxandroid-1.0.1.aar into /Users/dt/Developer/Code/Android/idea/Cl024/.okbuck/app
:okbuck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okbuck'.
> get app's sign config fail!

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':okbuck'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.lang.IllegalStateException: get app's sign config fail!
        at com.github.piasy.okbuck.helper.ProjectHelper.createKeystoreRule(ProjectHelper.groovy:306)
        at com.github.piasy.okbuck.helper.ProjectHelper$createKeystoreRule$4.call(Unknown Source)
        at com.github.piasy.okbuck.dependency.DependencyProcessor.processKeystore(DependencyProcessor.groovy:68)
        at com.github.piasy.okbuck.dependency.DependencyProcessor.process(DependencyProcessor.groovy:59)
        at com.github.piasy.okbuck.dependency.DependencyProcessor$process.call(Unknown Source)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator.generate(XBuckFileGenerator.groovy:58)
        at com.github.piasy.okbuck.generator.XBuckFileGenerator$generate.call(Unknown Source)
        at com.github.piasy.okbuck.OkBuckGradlePlugin.applyWithoutBuildVariant(OkBuckGradlePlugin.groovy:119)
        at com.github.piasy.okbuck.OkBuckGradlePlugin$_apply_closure3.doCall(OkBuckGradlePlugin.groovy:72)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more

BUILD FAILED

**Comment by Piasy** [comment]
@fengbugou 目前还没有针对1.5做适配，会尽快加上的。

**Comment by fengbugou** [comment]
谢谢，想用1.5的原因是想用官方的databind来替换掉butterknife，而databin d需要1.5。
拜托了
2015年11月17日 09:06，"Piasy" <notifications@github.com>写道：

**Comment by Piasy** [comment]
@fengbugou 可是目前buck似乎不支持data binding呀

**Comment by fengbugou** [comment]
！！我一会儿查查 谢谢！
2015年11月17日 09:10，"Piasy" <notifications@github.com>写道：

**Comment by Piasy** [comment]
Solved since v1.0.0-beta3
