### ISSUE TITLE
Error parsing resources to generate resource IDs 

### ISSUE THREAD

**Issue by AllenCoder** [Piasy/OkBuck#64]
buck install appDevDebug
[AndroidManifest.xml:3, AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='14'> but library uses targetSdkVersion='23'
Note: main manifest lacks a <uses-sdk android:targetSdkVersion> declaration, which defaults to value minSdkVersion or 1.
[AndroidManifest.xml:3, AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='14'> but library uses targetSdkVersion='20'
Note: main manifest lacks a <uses-sdk android:targetSdkVersion> declaration, which defaults to value minSdkVersion or 1.
[AndroidManifest.xml:3, AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='14'> but library uses targetSdkVersion='22'
Note: main manifest lacks a <uses-sdk android:targetSdkVersion> declaration, which defaults to value minSdkVersion or 1.
[AndroidManifest.xml:3, AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='14'> but library uses targetSdkVersion='23'
Note: main manifest lacks a <uses-sdk android:targetSdkVersion> declaration, which defaults to value minSdkVersion or 1.
Error parsing resources to generate resource IDs for /Users/allen/AndroidStudioProjects/juyoulicai_android_app/app/src/main/res.
com.facebook.buck.android.aapt.MiniAapt.ResourceParseException: Invalid definition of a resource: '@'
com.facebook.buck.android.aapt.MiniAapt$ResourceParseException: Invalid definition of a resource: '@'
	at com.facebook.buck.android.aapt.MiniAapt.processXmlFile(MiniAapt.java:504)
	at com.facebook.buck.android.aapt.MiniAapt.processXmlFilesForIds(MiniAapt.java:472)
	at com.facebook.buck.android.aapt.MiniAapt.execute(MiniAapt.java:167)
	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:63)
	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1156)
	at com.facebook.buck.rules.CachingBuildEngine.access$13(CachingBuildEngine.java:1139)
	at com.facebook.buck.rules.CachingBuildEngine$5$1.call(CachingBuildEngine.java:527)
	at com.facebook.buck.rules.CachingBuildEngine$5$1.call(CachingBuildEngine.java:1)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:65)
	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:1)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

BUILD FAILED: //app:res_main failed with exit code 1:
generate_resource_ids
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[-] DOWNLOADING... (0.00 B/S AVG, TOTAL: 0.00 B, 0 Artifacts)
[-] BUILDING...FINISHED 1.1s [100%] (234/241 JOBS, 4 UPDATED, 1.7% CACHE MISS)

**Comment by Piasy** [comment]
This is not OkBuck's problem, it's because your resource id contains `@` sign. Besides, it seems that your app's `targetSdkVersion` differs from libraries, which will also cause build fail, your app's `targetSdkVersion` should be greater than all libraries.

**Comment by AllenCoder** [comment]
my  resource id not contains @ sign

**Comment by Piasy** [comment]
It's due to the usage of `data binding` library, which is incompatible with BUCK.
